# Generated by Django 4.2.9 on 2024-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0027_alter_payment_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='owner_email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
