# Generated by Django 4.2.9 on 2024-04-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0029_vendor_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='owner_email',
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_email_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
