# Generated by Django 4.2.10 on 2024-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0030_remove_vendor_owner_email_vendor_owner_email_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='owner_email_json',
            field=models.JSONField(default=list),
        ),
    ]
