# Generated by Django 4.2.10 on 2024-04-08 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0031_alter_vendor_owner_email_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorUpdates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(max_length=255)),
                ('old_payment_method', models.CharField(max_length=255)),
                ('new_payment_method', models.CharField(max_length=255)),
                ('old_payment_cycle', models.CharField(max_length=255)),
                ('new_payment_cycle', models.CharField(max_length=255)),
                ('old_number', models.CharField(max_length=255)),
                ('new_number', models.CharField(max_length=255)),
                ('old_receiver_name', models.CharField(max_length=255)),
                ('new_receiver_name', models.CharField(max_length=255)),
                ('old_owner_phone', models.CharField(max_length=255)),
                ('new_owner_phone', models.CharField(max_length=255)),
                ('old_account_manager', models.CharField(max_length=255)),
                ('new_account_manager', models.CharField(max_length=255)),
                ('old_fully_refended', models.CharField(max_length=255)),
                ('new_fully_refended', models.CharField(max_length=255)),
                ('old_penalized', models.CharField(max_length=255)),
                ('new_panelized', models.CharField(max_length=255)),
                ('old_emails', models.CharField(max_length=255)),
                ('new_emails', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='log',
        ),
    ]
