# Generated by Django 4.2.10 on 2024-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0033_vendorupdates_created_at_vendorupdates_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorupdates',
            options={'verbose_name_plural': 'Vendor Updates'},
        ),
        migrations.AddField(
            model_name='vendorupdates',
            name='vendor_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
