# Generated by Django 4.2.9 on 2024-04-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0034_alter_vendorupdates_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidorders',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='cancellation_type',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='commission_percentage',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='commission_value',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='hybrid_payment',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='lastStatus',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='to_be_paid',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='total_discount',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='vendor_discount',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='vendor_discount_cap',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='vendor',
            name='commission_after_discount',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paidorders',
            name='order_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
