# Generated by Django 4.2.9 on 2024-04-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0035_remove_paidorders_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorupdates',
            name='new_commission_after_discount',
            field=models.CharField(default='true', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorupdates',
            name='old_commission_after_discount',
            field=models.CharField(default='false', max_length=255),
            preserve_default=False,
        ),
    ]
