# Generated by Django 4.2.9 on 2024-04-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0036_vendorupdates_new_commission_after_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='commission_after_discount',
        ),
    ]
