# Generated by Django 4.2.9 on 2024-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0037_remove_vendor_commission_after_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='commission_after_discount',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
