# Generated by Django 4.2.9 on 2024-04-17 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mms_api', '0039_vendoridname'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('payment_receiver_name', models.CharField(blank=True, max_length=255)),
                ('owner_email_json', models.JSONField(blank=True, default=list)),
                ('fully_refunded', models.BooleanField(blank=True)),
                ('penalized', models.BooleanField(blank=True)),
                ('commission_after_discount', models.BooleanField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_manager_vendor_details', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pay_period', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mms_api.paymentcycle')),
                ('pay_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mms_api.paymentmethod')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.vendoridname')),
            ],
        ),
    ]
